project:
  type: website

bibliography: references.bib
csl: csl/apa-cv.csl

website:
  title: "AD688: Fashion and Apparel Career Evaluation - Group 7"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
     

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
