project:
  type: website

bibliography: references.bib
csl: csl/apa.csl

website:
  title: "AD688: Fashion and Apparel Career Evaluation - Group 7"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - text: "Analysis"
        menu:
          - href: data_preparation.qmd
            text: Data Preparation
          - href: market_baseline.qmd
            text: Market Baseline
          - href: skill_gap_analysis.qmd
            text: Skill Gap Analysis
          - href: career_evaluation.qmd
            text: Career Evaluation
          - href: final_analytics.qmd
            text: Final Analytics
      - href: final_recommendations.qmd
        text: Final Recommendations
      - href: appendix.qmd
        text: Appendix

format:
  html:
    theme: [yeti, theme.scss]
    css: styles.css
    include-after-body: rack.html
    toc: true
    code-fold: true
    title-block-banner: "images/banner_background.jpg"
    title-block-banner-color: "white"

execute:
  echo: true
  eval: true
