[tool.poetry]
name = "ad688-fashion-apparel-evaluation-group7"
version = "0.1.0"
description = "AD688 O1 Project - Group 7"
authors = ["Zech Schweitzer <321160736+zechnschweitzer@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.5.3"
pandas = "^3.0.5"
seaborn = "^0.13.2"
plotly = "^7.0.0"
matplotlib = "^3.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
