[tool.poetry]
name = "ad688-fashion-apparel-evaluation-group7"
version = "0.0.1"
description = "Website for MET AD688 01 Group 7 Project"
authors = ["Zech Schweitzer <321160736+zechnschweitzer@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
